title: test just the docs
description: is this shit working
theme: just-the-docs

url: https://Rlhoove1.github.io/test


# For copy button on code
enable_copy_code_button: true


# Enable or disable heading anchors
heading_anchors: true


# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


